class CCCDInfo {
  late String Name;
  late String Id;
  late String NgaySinh;
  late String DiaChi;
  late String? NgayLamCCCD = "";
  late String TimeStamp;
  late String gioiTinh;
  String? maBuuGui = ""; // Postal code field

  // ✅ NEW: Firebase Queue Structure Fields
  late int index; // Sequential number (for display, not for ordering)
  late String status; // 'pending', 'processing', 'completed', 'error'
  late String createdAt; // ✅ CRITICAL: ISO 8601 timestamp for ordering
  String? processedAt; // ISO timestamp when processed
  String? errorReason; // Error message if status = 'error'

  // Firebase push key (auto-generated by Firebase)
  String? firebaseKey;

  CCCDInfo(this.Name, this.NgaySinh, this.Id) {
    TimeStamp = DateTime.now().millisecondsSinceEpoch.toString();
    gioiTinh = "";
    maBuuGui = null;

    // ✅ Initialize queue fields with defaults
    index = 0;
    status = 'pending';
    createdAt = DateTime.now().toIso8601String();
    processedAt = null;
    errorReason = null;
    firebaseKey = null;
  }

  fromJson(Map<String, dynamic> json) {
    Name = json['Name'] ?? '';
    Id = json['Id'] ?? '';
    NgaySinh = json['NgaySinh'] ?? '';
    TimeStamp =
        json['TimeStamp'] ?? DateTime.now().millisecondsSinceEpoch.toString();
    gioiTinh = json['gioiTinh'] ?? "";
    maBuuGui = json['maBuuGui'];
    DiaChi = json['DiaChi'] ?? '';
    NgayLamCCCD = json['NgayLamCCCD'];

    // ✅ Parse queue fields
    index = json['index'] ?? 0;
    status = json['status'] ?? 'pending';
    createdAt = json['createdAt'] ?? DateTime.now().toIso8601String();
    processedAt = json['processedAt'];
    errorReason = json['errorReason'];
    firebaseKey = json['firebaseKey'];
  }

  Map<dynamic, dynamic> toJsonFull() => {
        'Name': Name,
        'Id': Id,
        'NgaySinh': NgaySinh,
        'TimeStamp': TimeStamp,
        "DiaChi": DiaChi,
        "NgayLamCCCD": NgayLamCCCD ?? "",
        "gioiTinh": gioiTinh,
        "maBuuGui": maBuuGui ?? "",

        // ✅ Include queue fields
        'index': index,
        'status': status,
        'createdAt': createdAt,
        if (processedAt != null) 'processedAt': processedAt,
        if (errorReason != null) 'errorReason': errorReason,
      };

  Map<dynamic, dynamic> toJson() => {
        'Name': Name,
        'Id': Id,
        'NgaySinh': NgaySinh,
        'TimeStamp': TimeStamp,

        // ✅ Include queue fields in basic JSON
        'index': index,
        'status': status,
        'createdAt': createdAt,
        if (processedAt != null) 'processedAt': processedAt,
        if (errorReason != null) 'errorReason': errorReason,
      };

  // Method để tạo chuỗi copy theo format yêu cầu
  String toCopyFormat(int displayIndex) {
    return "$displayIndex\t${maBuuGui ?? ''}\t$Id\t$Name\t$NgaySinh\t$gioiTinh\t$DiaChi";
  }

  // ✅ Helper method để check status
  bool get isPending => status == 'pending';
  bool get isProcessing => status == 'processing';
  bool get isCompleted => status == 'completed';
  bool get isError => status == 'error';
}
